/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    podcasts: Podcast;
    posts: Post;
    categories: Category;
    people: Person;
    media: Media;
    pages: Page;
    submissions: Submission;
    subscribers: Subscriber;
    users: User;
    'error-logs': ErrorLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    podcasts: PodcastsSelect<false> | PodcastsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'error-logs': ErrorLogsSelect<false> | ErrorLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'about-page': AboutPage;
    'podcasts-page': PodcastsPage;
    'blogs-page': BlogsPage;
    'join-pages': JoinPage;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'podcasts-page': PodcastsPageSelect<false> | PodcastsPageSelect<true>;
    'blogs-page': BlogsPageSelect<false> | BlogsPageSelect<true>;
    'join-pages': JoinPagesSelect<false> | JoinPagesSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Release date future mein ho to episode website par "Next Episode" ban kar dikhega, aur us din se list mein aa jayega.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcasts".
 */
export interface Podcast {
  id: number;
  title: string;
  summary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Short description, cards aur Google ke liye (1–2 lines).
   */
  excerpt?: string | null;
  host?: (number | null) | Person;
  guests?: (number | Person)[] | null;
  /**
   * 📐 1280 × 440 px · Wide banner, JPG/WebP. Podcast cards aur Next Episode banner mein isi shape mein dikhta hai.
   */
  thumbnail: number | Media;
  /**
   * 📐 1240 × 850 px · Optional. Single podcast page banner ka right hissa: host + guest, neeche se kate hue, JPG/WebP. Khali ho to thumbnail use hoga.
   */
  heroImage?: (number | null) | Media;
  /**
   * Jis platform par episode hai, sirf us ka link paste karein.
   */
  links?: {
    youtube?: string | null;
    spotify?: string | null;
    soundcloud?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * URL ka hissa. Khali chhorein to "title" se khud ban jayega.
   */
  slug?: string | null;
  category: number | Category;
  releaseDate: string;
  /**
   * e.g. 42 min
   */
  duration?: string | null;
  /**
   * Homepage ke hero mein dikhayein.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Podcast hosts, guests aur blog authors. Ek dafa add karein, har jagah select karein.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  name: string;
  /**
   * e.g. Co-founder & CEO
   */
  designation?: string | null;
  company?: string | null;
  /**
   * LinkedIn profile URL
   */
  linkedin?: string | null;
  /**
   * 📐 800 × 900 px · Portrait (lambi) photo, chehra upar beech mein, JPG/WebP. Testimonials aur author box mein isi shape mein katti hai.
   */
  photo?: (number | null) | Media;
  /**
   * 📐 400 × 120 px · Transparent PNG ya SVG, logo ke aas paas khali jagah na ho. Cards par 22px oonchai mein dikhta hai.
   */
  companyLogo?: (number | null) | Media;
  /**
   * Agar bhara ho to About page ke testimonials slider mein dikhega.
   */
  testimonial?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Image ka chhota sa description (SEO aur accessibility ke liye).
   */
  alt: string;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * Podcasts aur blogs dono mein use hoti hain (AI, Design, Social...).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Optional. Category page (/podcasts?category=...) ke hero aur Google description mein dikhti hai (155 characters tak).
   */
  description?: string | null;
  /**
   * URL ka hissa. Khali chhorein to "name" se khud ban jayega.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Blog cards par dikhne wali 2–3 lines.
   */
  excerpt: string;
  /**
   * 📐 1600 × 900 px · Landscape 16:9, JPG/WebP. Blog cards aur article ke upar isi shape mein dikhti hai.
   */
  featuredImage: number | Media;
  /**
   * H2 headings khud "In this Article" (Table of Contents) mein aa jati hain.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Article ke neeche "Frequently Asked Questions" (Google FAQ schema bhi).
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * URL ka hissa. Khali chhorein to "title" se khud ban jayega.
   */
  slug?: string | null;
  category: number | Category;
  author?: (number | null) | Person;
  /**
   * Pehli dafa publish par khud lag jati hai.
   */
  publishedAt?: string | null;
  /**
   * Sirf tab badalti hai jab publish ke baad content waqai change ho.
   */
  contentUpdatedAt?: string | null;
  publishedHash?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Privacy Policy, Terms & Conditions jaise simple text pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * URL ka hissa. Khali chhorein to "title" se khud ban jayega.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  type: 'contact' | 'guest' | 'host';
  fullName: string;
  email: string;
  phone?: string | null;
  company: string;
  linkedin: string;
  enquiry?: string | null;
  status?: ('new' | 'contacted' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "error-logs".
 */
export interface ErrorLog {
  id: number;
  message?: string | null;
  path?: string | null;
  status?: number | null;
  stack?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'podcasts';
        value: number | Podcast;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'error-logs';
        value: number | ErrorLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcasts_select".
 */
export interface PodcastsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  excerpt?: T;
  host?: T;
  guests?: T;
  thumbnail?: T;
  heroImage?: T;
  links?:
    | T
    | {
        youtube?: T;
        spotify?: T;
        soundcloud?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  category?: T;
  releaseDate?: T;
  duration?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  category?: T;
  author?: T;
  publishedAt?: T;
  contentUpdatedAt?: T;
  publishedHash?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  designation?: T;
  company?: T;
  linkedin?: T;
  photo?: T;
  companyLogo?: T;
  testimonial?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  type?: T;
  fullName?: T;
  email?: T;
  phone?: T;
  company?: T;
  linkedin?: T;
  enquiry?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "error-logs_select".
 */
export interface ErrorLogsSelect<T extends boolean = true> {
  message?: T;
  path?: T;
  status?: T;
  stack?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Homepage ka saara text. Podcasts aur blogs khud latest content se aate hain.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * Right side par "Featured" podcast dikhta hai (Podcasts mein Featured tick karein).
   */
  hero?: {
    title?: string | null;
    text?: string | null;
    hostButtonLabel?: string | null;
    hostButtonLink?: string | null;
    guestButtonLabel?: string | null;
    guestButtonLink?: string | null;
  };
  podcasts?: {
    heading?: string | null;
    buttonLabel?: string | null;
  };
  blogs?: {
    label?: string | null;
    heading?: string | null;
  };
  contact?: {
    heading?: string | null;
    text?: string | null;
    joinPrompt?: string | null;
    joinLinkLabel?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * About Us page. Testimonials "Hosts & Guests" se aate hain (jin ka Testimonial bhara ho).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero?: {
    title?: string | null;
    /**
     * 📐 1424 × 688 px · Optional. Yellow hero ka right hissa (guests ki photos). Khali ho to default image.
     */
    image?: (number | null) | Media;
  };
  whatWeDo?: {
    heading?: string | null;
    text?: string | null;
    /**
     * 📐 1132 × 576 px · Optional. Event / stage ki landscape photo. Khali ho to default image.
     */
    image?: (number | null) | Media;
  };
  vision?: {
    heading?: string | null;
    /**
     * Khali line chhorne se naya paragraph banta hai.
     */
    text?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Podcasts listing page (/podcasts) ka text. Episodes "Podcasts" collection se aate hain.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcasts-page".
 */
export interface PodcastsPage {
  id: number;
  hero?: {
    title?: string | null;
    description?: string | null;
  };
  moreHeading?: string | null;
  loadMoreLabel?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Blogs listing page (/blogs) ka text. Articles "Blogs" collection se aate hain.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs-page".
 */
export interface BlogsPage {
  id: number;
  hero?: {
    title?: string | null;
    description?: string | null;
  };
  moreHeading?: string | null;
  loadMoreLabel?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * /join-as-guest aur /join-as-host pages ka text.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "join-pages".
 */
export interface JoinPage {
  id: number;
  banner?: string | null;
  guest?: {
    tab?: string | null;
    title?: string | null;
    text?: string | null;
    seoTitle?: string | null;
    seoDescription?: string | null;
  };
  host?: {
    tab?: string | null;
    title?: string | null;
    text?: string | null;
    seoTitle?: string | null;
    seoDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Poori website par aane wali cheezein: menu, footer, shared sections, social links aur SEO.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  header?: {
    /**
     * 📐 300 × 120 px · Optional. Transparent PNG/SVG logo. Khali ho to "DESK TALKS." text logo dikhega.
     */
    logo?: (number | null) | Media;
    /**
     * Upar wale menu ke links, isi tarteeb mein.
     */
    nav?:
      | {
          label: string;
          /**
           * Jaise /about, /#contact ya https://...
           */
          link: string;
          id?: string | null;
        }[]
      | null;
    ctaLabel?: string | null;
    ctaLink?: string | null;
  };
  footer?: {
    /**
     * 📐 300 × 120 px · Optional. Dark footer ke liye safaid (white) logo, transparent PNG/SVG.
     */
    logo?: (number | null) | Media;
    /**
     * Footer mein logo ke saath wale links.
     */
    links?:
      | {
          label: string;
          /**
           * Jaise /about, /#contact ya https://...
           */
          link: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Copyright line ke saath wale links.
     */
    bottomLinks?:
      | {
          label: string;
          /**
           * Jaise /about, /#contact ya https://...
           */
          link: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Saal (year) khud aage lag jata hai.
     */
    copyright?: string | null;
  };
  community?: {
    title?: string | null;
    text?: string | null;
    buttonLabel?: string | null;
    buttonLink?: string | null;
    /**
     * 📐 720 × 768 px · Optional. Transparent PNG (globe / people graphic). Khali ho to default graphic dikhega.
     */
    image?: (number | null) | Media;
  };
  subscribe?: {
    heading?: string | null;
    placeholder?: string | null;
    buttonLabel?: string | null;
    successMessage?: string | null;
  };
  blogCta?: {
    heading?: string | null;
    text?: string | null;
    buttonLabel?: string | null;
    buttonUrl?: string | null;
  };
  /**
   * "The DeskTalk community is growing!" section ke company logos.
   */
  partnerLogos?:
    | {
        name: string;
        /**
         * 📐 440 × 100 px · Transparent PNG ya SVG, ek rang (grey) ka logo. Teal section mein khud safaid ho jata hai.
         */
        logo: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Footer ke icons. Khali chhora hua icon nahi dikhega.
   */
  social?: {
    youtube?: string | null;
    linkedin?: string | null;
    instagram?: string | null;
    soundcloud?: string | null;
    spotify?: string | null;
  };
  seo?: {
    /**
     * Jin pages ki apni description na ho, un par Google mein yeh dikhegi (155 characters tak).
     */
    defaultDescription?: string | null;
    /**
     * 📐 1200 × 630 px · Facebook/LinkedIn/WhatsApp par link share karne par dikhne wali image. Khali ho to default image.
     */
    shareImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        text?: T;
        hostButtonLabel?: T;
        hostButtonLink?: T;
        guestButtonLabel?: T;
        guestButtonLink?: T;
      };
  podcasts?:
    | T
    | {
        heading?: T;
        buttonLabel?: T;
      };
  blogs?:
    | T
    | {
        label?: T;
        heading?: T;
      };
  contact?:
    | T
    | {
        heading?: T;
        text?: T;
        joinPrompt?: T;
        joinLinkLabel?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        image?: T;
      };
  whatWeDo?:
    | T
    | {
        heading?: T;
        text?: T;
        image?: T;
      };
  vision?:
    | T
    | {
        heading?: T;
        text?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcasts-page_select".
 */
export interface PodcastsPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        description?: T;
      };
  moreHeading?: T;
  loadMoreLabel?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs-page_select".
 */
export interface BlogsPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        description?: T;
      };
  moreHeading?: T;
  loadMoreLabel?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "join-pages_select".
 */
export interface JoinPagesSelect<T extends boolean = true> {
  banner?: T;
  guest?:
    | T
    | {
        tab?: T;
        title?: T;
        text?: T;
        seoTitle?: T;
        seoDescription?: T;
      };
  host?:
    | T
    | {
        tab?: T;
        title?: T;
        text?: T;
        seoTitle?: T;
        seoDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  header?:
    | T
    | {
        logo?: T;
        nav?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
        ctaLabel?: T;
        ctaLink?: T;
      };
  footer?:
    | T
    | {
        logo?: T;
        links?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
        bottomLinks?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
        copyright?: T;
      };
  community?:
    | T
    | {
        title?: T;
        text?: T;
        buttonLabel?: T;
        buttonLink?: T;
        image?: T;
      };
  subscribe?:
    | T
    | {
        heading?: T;
        placeholder?: T;
        buttonLabel?: T;
        successMessage?: T;
      };
  blogCta?:
    | T
    | {
        heading?: T;
        text?: T;
        buttonLabel?: T;
        buttonUrl?: T;
      };
  partnerLogos?:
    | T
    | {
        name?: T;
        logo?: T;
        id?: T;
      };
  social?:
    | T
    | {
        youtube?: T;
        linkedin?: T;
        instagram?: T;
        soundcloud?: T;
        spotify?: T;
      };
  seo?:
    | T
    | {
        defaultDescription?: T;
        shareImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "YouTubeBlock".
 */
export interface YouTubeBlock {
  url: string;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'youtube';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}